### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by BlackRider99** [ryandw11/Ultra-Chat#1]
Hi, i'm getting a error when i speak in the chat.
Spigot 1.9.2
http://pastebin.com/bfYNFbes
Sorry the bad english

**Comment by ryandw11** [comment]
Thank you for the report. I will look right into it.

**Comment by ryandw11** [comment]
Hello. Thank you for your report. The bug should be fixed. Please download version 1.7.2-1 for 1.9.
