### ISSUE TITLE
Darkblue color not working.

### ISSUE THREAD

**Issue by PabloMG123** [ryandw11/Ultra-Chat#11]
Hello, when i use the /color command i have access to all colors without a problem, except dark blue that appears like blue color chat (&9) and not dark blue (&1).

I use the last version. Thanks

**Comment by ryandw11** [comment]
I get the same results. I can't find an easy reason why though. I will look into it.

**Comment by PabloMG123** [comment]
waiting for an update then.

**Comment by ryandw11** [comment]
Fixed on Version 2.2-Pre1 for 1.13. Working on a patch for 1.12+.
