### ISSUE TITLE
How to Activate channels

### ISSUE THREAD

**Issue by Skeec54** [ryandw11/Ultra-Chat#13]
How can i activating channels?
(ignore my englisch xD)

**Comment by ryandw11** [comment]
I'm sorry. What do you mean by activate channels? Do you mean creating them or switching to a different channel.

**Comment by Skeec54** [comment]
i mean this: 
http://prntscr.com/ltmeza
How to activate it

**Comment by ryandw11** [comment]
in the config look for the `chat_format: 'normal'` option. Change that to channel. `chat_format: 'channel'`
