### ISSUE TITLE
How i can create a channel?

### ISSUE THREAD

**Issue by Cosmarul** [ryandw11/Ultra-Chat#7]
How i can create a channel with prefix..

**Comment by KingTux2** [comment]
Make sure this Channels: false says this Channels: true
and it should generate a config.
Here is more info
https://github.com/ryandw11/Ultra-Chat/wiki/Channels

**Comment by Cosmarul** [comment]
Oh, ty. But i can make a channel with radius, like a local chat?

**Comment by ryandw11** [comment]
No you can not at the moment.

**Comment by KingTux2** [comment]
@ryandw11  do that! Enable radius chat! It won't be that hard.

**Comment by ryandw11** [comment]
Completed in 2.1.0. Sorry for the long wait.
